# Generated by Django 3.2.8 on 2021-11-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='github_users',
            name='html_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
