# Generated by Django 4.0 on 2021-12-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_github_users_html_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='github_users',
            options={'ordering': ['-id']},
        ),
    ]
